# Generated by Django 5.2 on 2025-04-07 14:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(default='example@mail.ru', max_length=254)),
                ('surname', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=api.models.upload_avatar_path)),
            ],
        ),
    ]
