# Generated by Django 5.2 on 2025-04-16 09:27

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopapp.models.upload_image_category_path),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@mail.ru', max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('deliveryType', models.CharField(choices=[('express', 'Экспресс-доставка'), ('delivery', 'Обычная доставка')], max_length=100)),
                ('paymentType', models.CharField(choices=[('online', 'Онлайн оплата'), ('online_any', 'Онлайн оплата (любая)')], max_length=20)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(default='Processing...', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(to='shopapp.product')),
            ],
        ),
    ]
