# Generated by Django 5.2 on 2025-04-16 10:38

import django.db.models.deletion
import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_order_basket_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopapp.models.upload_image_category_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopapp.basket'),
        ),
    ]
