# Generated by Django 5.2 on 2025-04-16 10:49

import django.db.models.deletion
import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_alter_category_image_alter_order_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket_items',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='shopapp.basketitems'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopapp.models.upload_image_category_path),
        ),
    ]
