# Generated by Django 5.2 on 2025-04-16 10:51

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_order_basket_items_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='basket_items',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopapp.models.upload_image_category_path),
        ),
    ]
