# Generated by Django 5.2 on 2025-04-28 09:00

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0030_alter_category_image_delete_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopapp.models.upload_image_category_path),
        ),
    ]
